sonar.projectKey=2026_nycu_cloudNative
sonar.projectName=2026_nycu_cloudNative

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/tests

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/docs/**,**/tools/**,**/.m2/**,**/*.png,**/*.svg,**/*.jar
sonar.test.inclusions=backend/src/test/java/**/*.java,frontend/tests/**/*.ts
