spring.datasource.url=jdbc:mysql://localhost:3306/lab_system
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update 

# 重開就傳新建表
# spring.jpa.hibernate.ddl-auto=create 

spring.jpa.show-sql=true
server.port=8080

# Google OAuth2 Client ID for Token Verification (Support Env Variable)
google.client.id=${GOOGLE_CLIENT_ID:918686891468-545ppen19kij93c600ipu7prhnsi04qi.apps.googleusercontent.com}